# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd array; make clean
	cd arraymember; make clean
	cd arraymember2; make clean
	cd callback; make clean
	cd callback2; make clean
	cd constraint; make clean
	cd database; make clean
	cd defarg; make clean
	cd manual; make clean
	cd multinherit; make clean
	cd native; make clean
	cd nested; make clean
	cd objc; make clean
	cd runtime; make clean
	cd shadow; make clean
	cd simple; make clean
	cd typemaps; make clean
	rm -f *~ .~* core

