# Generated automatically from Makefile.in by configure.
CC      = gcc
INCLUDE = -I../../Include
LIB     = -L../.. -lgifplot
SRCS    = 
TARGET  = 

all:
	$(CC) $(SRCS) $(INCLUDE) $(LIB) -lm -o $(TARGET)


SUBDIRS = clip hello inset ortho plot plot3d plot3dc plot3di plot2dc plot2di view

clean:
	@for i in $(SUBDIRS); do \
	  (cd $$i; $(MAKE) clean;) \
	done;

