# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd array; make clean
	cd blttix; make clean
	cd c++; make clean
	cd constant; make clean
	cd constraint; make clean
	cd defarg; make clean
	cd graph; make clean
	cd itcl; make clean
	cd objc; make clean
	cd runtime; make clean
	cd shadow; make clean
	cd simple; make clean
	cd tcl_plugin; make clean
	cd tree; make clean
	cd typemaps; make clean
	rm -f *~ .~* core
