# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd SWIGtoXS; make clean
	cd c++; make clean
	cd constraint; make clean
	cd defarg; make clean
	cd except; make clean
	cd graph; make clean
	cd multinherit; make clean
	cd nested; make clean
	cd objc; make clean
	cd runtime; make clean
	cd shadow; make clean
	cd simple; make clean
	cd tree; make clean
	cd typemaps; make clean
	rm -f *~ .~* core


