# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd graph1; make clean
	cd graph2; make clean
	cd graph3; make clean
	cd graph4; make clean
	rm -f *~ .~* core
