# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd argv; make clean
	cd array2; make clean
	cd ignore; make clean
	cd output; make clean
	cd return; make clean
	cd simple; make clean
	rm -f *~ .~* core
