CC     = gcc
SRCS   = tree.c
TARGET = tree
IFILE  = tree.i
MKDIR  = ..

all::
	$(MAKE) -f $(MKDIR)/Makefile SRCS='$(SRCS)' TARGET='tree' IFILE=$(IFILE) CC=$(CC)

clean::
	rm -f tree *_wrap* *.o *~ .~* core








