# This file was automatically generated by SWIG
package example;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package examplec;
bootstrap example;
var_example_init();
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package example;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package example;

*fact = *examplec::fact;
*mod = *examplec::mod;
*get_time = *examplec::get_time;
*newname = *examplec::newname;

# ------- VARIABLE STUBS --------

package example;

*My_variable = *examplec::My_variable;
*FOO = *examplec::FOO;
*BAR = *examplec::BAR;
*PI = *examplec::PI;
1;
