# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd gd1; make clean
	cd gd2; make clean
	cd pde1; make clean
	cd pde2; make clean
	cd pde3; make clean
	cd pde4; make clean
	cd pde_gd; make clean
	cd widget; make clean
	rm -f *~ .~* core
