# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd argv; make clean
	cd argv2; make clean
	cd arraymember; make clean
	cd database; make clean
	cd file; make clean
	cd ignore; make clean
	cd integer; make clean
	cd output; make clean
	cd passref; make clean
	cd reference; make clean
	cd return; make clean
	rm -f *~ .~* core


