# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd argv; make clean
	cd constants; make clean
	cd constrain; make clean
	cd database; make clean
	cd interp; make clean
	cd output; make clean
	cd retbyref; make clean
	cd return; make clean
	rm -f *~ .~* core

