# This makefile is only used to clean up

all:
	@echo 'type make in each subdirectory to build each example'

clean:
	cd inherit; make clean
	cd list; make clean
	cd multinherit; make clean
	cd shapes; make clean
	cd struct; make clean
	rm -f *~ .~* core
